import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { configureBudgetPeriod, getCurrentBudgetPeriod, getBudgetPeriod, getReserveTransfers, transferReserve, type ConfigureBudgetPeriodRequest } from '../api/budgetPeriodApi'
import type { BudgetSource } from '../../transaction/api/transactionApi'
export const budgetPeriodQueryKeys = { all: ['budget-periods'] as const, current: (ledgerId: number, at?: string) => ['budget-periods', ledgerId, 'current', at] as const, detail: (ledgerId: number, startDate: string) => ['budget-periods', ledgerId, startDate] as const, reserveTransfers: (ledgerId: number, startDate: string) => ['budget-periods', ledgerId, startDate, 'reserve-transfers'] as const }
export function useCurrentBudgetPeriodQuery(ledgerId: number | undefined, at?: string) { return useQuery({ queryKey: ledgerId ? budgetPeriodQueryKeys.current(ledgerId, at) : budgetPeriodQueryKeys.all, queryFn: () => getCurrentBudgetPeriod(ledgerId!, at), enabled: Boolean(ledgerId), retry: false }) }
export function useBudgetPeriodQuery(ledgerId: number | undefined, startDate: string | undefined) { return useQuery({ queryKey: ledgerId && startDate ? budgetPeriodQueryKeys.detail(ledgerId, startDate) : budgetPeriodQueryKeys.all, queryFn: () => getBudgetPeriod(ledgerId!, startDate!), enabled: Boolean(ledgerId && startDate), retry: false }) }
export function useConfigureBudgetPeriodMutation(ledgerId: number | undefined, startDate: string | undefined) { const client = useQueryClient(); return useMutation({ mutationFn: (request: ConfigureBudgetPeriodRequest) => configureBudgetPeriod(ledgerId!, startDate!, request), onSuccess: () => client.invalidateQueries({ queryKey: budgetPeriodQueryKeys.all }) }) }
/** 예비비 옮기기 이력 — 예산 설정 화면의 '옮긴 기록' 목록에 씁니다. */
export function useReserveTransfersQuery(ledgerId: number | undefined, startDate: string | undefined) { return useQuery({ queryKey: ledgerId && startDate ? budgetPeriodQueryKeys.reserveTransfers(ledgerId, startDate) : budgetPeriodQueryKeys.all, queryFn: () => getReserveTransfers(ledgerId!, startDate!), enabled: Boolean(ledgerId && startDate), retry: false }) }
export function useTransferReserveMutation(ledgerId: number | undefined, startDate: string | undefined) { const client = useQueryClient(); return useMutation({ mutationFn: ({ amount, target }: { amount: number; target: BudgetSource }) => transferReserve(ledgerId!, startDate!, amount, target), onSuccess: () => { client.invalidateQueries({ queryKey: budgetPeriodQueryKeys.all }) } }) }
