ALTER TABLE user_notifications
    MODIFY COLUMN type ENUM(
        'INVITATION', 'BUDGET', 'MONTH_CLOSED', 'SYSTEM',
        'BUDGET_THRESHOLD_80', 'BUDGET_THRESHOLD_100',
        'BUDGET_PERIOD_PREPARATION', 'WEEKLY_GUIDE',
        'BUDGET_CHANGED', 'RESERVE_TRANSFER'
    ) NOT NULL;
