import { apiRequest } from '../../../shared/api/client'
export type ImportSourceType = 'RECEIPT' | 'CARD_APP_SCREENSHOT'
export type ImportImageInput = { image: File; sourceType: ImportSourceType }
export type ImportSessionCandidate = { candidateId: number; occurredOn: string; amount: number; merchant: string; suggestedCategoryId: number | null; defaultBudgetSource: import('../../transaction/api/transactionApi').BudgetSource | null; duplicateSuspected: boolean; duplicateTransactionId: number | null; sourceType: ImportSourceType; selectedByDefault: boolean }
export type ImportSessionPreview = { sessionId: number; candidates: ImportSessionCandidate[]; omittedCount: number }
export type SaveImportSessionCandidate = { candidateId: number; amount: number; occurredOn: string; merchant: string; categoryId: number | null; budgetSource: import('../../transaction/api/transactionApi').BudgetSource | null; selected: boolean; paymentMethod?: { type: 'CASH' | 'CARD' | 'OTHER'; displayName?: string | null }; sharedWithPartner?: boolean | null }
export function previewImportSession(ledgerId: number, inputs: ImportImageInput[]) { const body = new FormData(); inputs.forEach(({ sourceType }) => body.append('sourceTypes', sourceType)); inputs.forEach(({ image }) => body.append('images', image)); return apiRequest<ImportSessionPreview>(`/api/ledgers/${ledgerId}/transaction-imports/previews`, { method: 'POST', body }) }
export type SavedImportCandidate = { candidateId: number; transaction: import('../../transaction/api/transactionApi').TransactionSummary }
export function saveImportSession(ledgerId: number, sessionId: number, candidates: SaveImportSessionCandidate[]) { return apiRequest<{ created: SavedImportCandidate[] }>(`/api/ledgers/${ledgerId}/transaction-imports`, { method: 'POST', body: { sessionId, candidates } }) }
