import { FileImage, Keyboard, X } from 'lucide-react'
import { useEffect, useMemo, useRef, useState, type FormEvent, type KeyboardEvent } from 'react'
import { useNavigate } from 'react-router-dom'
import { useMeQuery } from '../../auth/model/authQueries'
import { useCategoriesQuery } from '../../category/model/categoryQueries'
import type { BudgetSource, PaymentMethod, TransactionType } from '../api/transactionApi'
import { useCreateV1TransactionMutation } from '../model/transactionQueries'
import { formatDateInput } from '../../../shared/lib/date'
import type { TransactionEntryPreset } from '../../../shared/ui/TransactionEntryContext'
import { DatePicker } from '../../../shared/ui/DatePicker'

type Props = { open: boolean; onClose: () => void; preset?: TransactionEntryPreset }
export function TransactionEntrySheet({ open, onClose, preset }: Props) {
  const navigate = useNavigate()
  const me = useMeQuery()
  const ledgerId = me.data?.currentLedger.id
  const isSharedLedger = me.data?.currentLedger.type === 'GROUP' || me.data?.currentLedger.type === 'SHARED'
  const categories = useCategoriesQuery(ledgerId)
  const mutation = useCreateV1TransactionMutation(ledgerId)
  const [type, setType] = useState<TransactionType>(preset?.type ?? 'EXPENSE')
  const [transferType, setTransferType] = useState<'OWN_ACCOUNTS' | 'OUTBOUND' | 'INBOUND'>('OWN_ACCOUNTS')
  const [amount, setAmount] = useState(preset?.amount ?? '')
  const [merchant, setMerchant] = useState('')
  const [occurredOn, setOccurredOn] = useState(preset?.transactionDate ?? formatDateInput())
  const [categoryId, setCategoryId] = useState('')
  const [memo, setMemo] = useState(preset?.memo ?? '')
  const [sourceType, setSourceType] = useState<BudgetSource['type']>('PERSONAL')
  const [sharedWithPartner, setSharedWithPartner] = useState(false)
  const [paymentMethod, setPaymentMethod] = useState<PaymentMethod>('CASH')
  const [paymentDisplayName, setPaymentDisplayName] = useState('')
  const [installmentMonths, setInstallmentMonths] = useState(1)
  const [monthlyInterest, setMonthlyInterest] = useState('0')
  const [keepOpen, setKeepOpen] = useState(false)
  const dialogRef = useRef<HTMLElement>(null)
  const amountRef = useRef<HTMLInputElement>(null)
  const selectableCategories = useMemo(() => categories.data?.filter((category) => category.type === type) ?? [], [categories.data, type])
  useEffect(() => { if (!open) return; const previous=document.activeElement instanceof HTMLElement?document.activeElement:null; const frame=requestAnimationFrame(()=>amountRef.current?.focus()); return ()=>{cancelAnimationFrame(frame);previous?.focus()} }, [open])
  if (!open) return null
  const budgetExpense = type === 'EXPENSE' || (type === 'TRANSFER' && transferType === 'OUTBOUND')
  const source: BudgetSource = { type: sourceType, ownerUserId: sourceType === 'PERSONAL' ? me.data?.user.id ?? null : null }
  function submit(event: FormEvent) {
    event.preventDefault()
    mutation.mutate({ type, transferType: type === 'TRANSFER' ? transferType : null, amount: Number(amount), merchant: merchant.trim(), occurredOn, categoryId: Number(categoryId), memo: memo || null, scope: source, budgetSource: budgetExpense ? source : null, sharedWithPartner: isSharedLedger && sourceType === 'PERSONAL' ? sharedWithPartner : null, paymentMethod: paymentDisplayName ? { type: paymentMethod, displayName: paymentDisplayName } : { type: paymentMethod }, installment: type === 'EXPENSE' && paymentMethod === 'CARD' && installmentMonths > 1 ? { months: installmentMonths, monthlyInterest: Number(monthlyInterest) } : null }, { onSuccess: () => { if (keepOpen) { setAmount(''); setMerchant(''); setMemo(''); amountRef.current?.focus() } else onClose() } })
  }
  function trapFocus(event: KeyboardEvent<HTMLElement>) { if (event.key === 'Escape') { onClose(); return } if (event.key !== 'Tab') return; const items=dialogRef.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),a[href]'); if (!items?.length) return; const first=items[0],last=items[items.length-1]; if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()} }
  return <div className="transaction-entry-backdrop fixed inset-0 z-50 flex items-end justify-center min-[1041px]:items-stretch min-[1041px]:justify-end" onMouseDown={(event)=>event.target===event.currentTarget&&onClose()} role="presentation"><section aria-labelledby="transaction-entry-title" aria-modal="true" className="transaction-entry-sheet max-h-[86dvh] w-full overflow-y-auto rounded-t-[var(--wl-radius-sheet)] px-5 pb-[calc(1.5rem+env(safe-area-inset-bottom))] pt-5 sm:max-w-xl min-[1041px]:h-full min-[1041px]:max-h-none min-[1041px]:rounded-none" onKeyDown={trapFocus} ref={dialogRef} role="dialog"><div className="flex items-center justify-between"><span className="size-11"/><h2 className="text-xl font-bold" id="transaction-entry-title">빠른 기록</h2><button aria-label="거래 입력 닫기" className="flex size-11 items-center justify-center rounded-xl hover:bg-[var(--wl-color-surface-subtle)]" onClick={onClose} type="button"><X aria-hidden="true"/></button></div><div className="mt-4 grid grid-cols-2 gap-2"><button aria-pressed="true" className="flex min-h-11 items-center justify-center gap-2 rounded-xl bg-[var(--wl-brand-100)] text-sm font-bold text-[var(--wl-brand-700)]" type="button"><Keyboard aria-hidden="true" size={17}/>직접 입력</button><button className="flex min-h-11 items-center justify-center gap-2 rounded-xl border border-[var(--wl-color-border)] text-sm font-bold" onClick={()=>{onClose();navigate('/transactions/import')}} type="button"><FileImage aria-hidden="true" size={17}/>이미지 가져오기</button></div>
    <form className="mt-5 space-y-4" onSubmit={submit}><fieldset><legend className="sr-only">거래 유형</legend><div className="grid grid-cols-3 gap-2">{([['EXPENSE','지출'],['INCOME','수입'],['TRANSFER','이체']] as const).map(([value,label])=><button aria-pressed={type===value} className="min-h-11 rounded-xl text-sm font-bold aria-pressed:bg-[var(--wl-brand-100)] aria-pressed:text-[var(--wl-brand-700)]" key={value} onClick={()=>{setType(value);setCategoryId('')}} type="button">{label}</button>)}</div></fieldset>{type==='TRANSFER'?<label className="block text-sm font-bold" htmlFor="entry-transfer-type">이체 종류<select className="mt-2 h-12 w-full px-4" id="entry-transfer-type" onChange={(e)=>setTransferType(e.target.value as typeof transferType)} value={transferType}><option value="OWN_ACCOUNTS">내 계좌 간 이체</option><option value="OUTBOUND">다른 곳으로 송금</option><option value="INBOUND">외부에서 입금</option></select></label>:null}<label className="block text-sm font-bold" htmlFor="entry-amount">금액<input className="mt-2 h-14 w-full px-4 text-right text-2xl font-bold tabular-nums" id="entry-amount" inputMode="numeric" min="1" onChange={(e)=>setAmount(e.target.value)} ref={amountRef} required type="number" value={amount}/></label><label className="block text-sm font-bold" htmlFor="entry-merchant">사용처<input className="mt-2 h-12 w-full px-4" id="entry-merchant" maxLength={100} onChange={(e)=>setMerchant(e.target.value)} placeholder={type==='TRANSFER'?'상대 계좌 또는 상대방':'예: 동네마트'} required value={merchant}/></label><label className="block text-sm font-bold" htmlFor="entry-category">카테고리<select className="mt-2 h-12 w-full px-4" id="entry-category" onChange={(e)=>setCategoryId(e.target.value)} required value={categoryId}><option value="">선택해주세요</option>{selectableCategories.map((category)=><option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label className="block text-sm font-bold">날짜<DatePicker ariaLabel="거래 날짜" className="mt-2 w-full" onChange={setOccurredOn} value={occurredOn}/></label>
    {isSharedLedger?<fieldset><legend className="text-sm font-bold">거래 예산</legend><div className="mt-2 grid grid-cols-2 gap-2">{([['PERSONAL','내 예산'],['SHARED','공동 예산']] as const).map(([value,label])=><button aria-pressed={sourceType===value} className="min-h-11 rounded-xl border border-[var(--wl-color-border)] text-sm font-bold aria-pressed:border-[var(--wl-brand-600)] aria-pressed:bg-[var(--wl-brand-100)]" key={value} onClick={()=>setSourceType(value)} type="button">{label}</button>)}</div>{sourceType==='PERSONAL'?<label className="mt-3 flex min-h-11 items-center gap-3 text-sm font-bold"><input checked={sharedWithPartner} onChange={(e)=>setSharedWithPartner(e.target.checked)} type="checkbox"/>이 거래를 상대방과 공유</label>:null}</fieldset>:null}
    {type==='EXPENSE'?<fieldset><legend className="text-sm font-bold">결제수단</legend><div className="mt-2 grid grid-cols-3 gap-2">{(['CASH','CARD','OTHER'] as PaymentMethod[]).map((value)=><button aria-pressed={paymentMethod===value} className="min-h-11 rounded-xl border border-[var(--wl-color-border)] text-sm font-bold aria-pressed:bg-[var(--wl-brand-100)]" key={value} onClick={()=>{setPaymentMethod(value);if(value!=='CARD')setInstallmentMonths(1)}} type="button">{value==='CASH'?'현금':value==='CARD'?'카드':'기타'}</button>)}</div><label className="mt-3 block text-sm font-bold" htmlFor="payment-name">결제수단 이름 (선택)<input className="mt-2 h-12 w-full px-4" id="payment-name" onChange={(e)=>setPaymentDisplayName(e.target.value)} placeholder="예: 생활비 카드" value={paymentDisplayName}/></label>{paymentMethod==='CARD'?<div className="mt-3 grid grid-cols-2 gap-3"><label className="text-sm font-bold" htmlFor="installment-months">할부 개월<select className="mt-2 h-12 w-full px-3" id="installment-months" onChange={(e)=>setInstallmentMonths(Number(e.target.value))} value={installmentMonths}><option value="1">일시불</option>{[2,3,6,10,12,18,24].map((months)=><option key={months} value={months}>{months}개월</option>)}</select></label>{installmentMonths>1?<label className="text-sm font-bold" htmlFor="monthly-interest">월 이자<input className="mt-2 h-12 w-full px-3 text-right" id="monthly-interest" min="0" onChange={(e)=>setMonthlyInterest(e.target.value)} type="number" value={monthlyInterest}/></label>:null}</div>:null}</fieldset>:null}<label className="block text-sm font-bold" htmlFor="entry-memo">메모 (선택)<textarea className="mt-2 min-h-20 w-full p-4" id="entry-memo" onChange={(e)=>setMemo(e.target.value)} value={memo}/></label>{mutation.isError?<p className="text-sm text-[var(--wl-color-danger)]" role="alert">필수값과 선택한 예산을 확인해주세요.</p>:null}<label className="flex min-h-11 items-center gap-3 text-sm font-bold"><input checked={keepOpen} onChange={(e)=>setKeepOpen(e.target.checked)} type="checkbox"/>저장 후 계속 입력</label><button className="min-h-12 w-full rounded-xl bg-[var(--wl-color-primary)] text-sm font-bold text-white disabled:bg-slate-300" disabled={mutation.isPending} type="submit">{mutation.isPending?'저장 중...':'저장하기'}</button></form></section></div>
}
