import { Bell, Plus } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useDashboardSummaryQuery } from '../features/budget/model/budgetQueries'
import { useNotificationsQuery } from '../features/notification/model/notificationQueries'
import type { DashboardBudget } from '../features/budget/api/budgetApi'
import { formatWon } from '../shared/lib/money'
import { EmptyState, ErrorState, PageHeader, SurfaceCard } from '../shared/ui/DesignPrimitives'
import { useTransactionEntry } from '../shared/ui/TransactionEntryContext'

export function DashboardPage() {
  const dashboard = useDashboardSummaryQuery()
  const notifications = useNotificationsQuery()
  const { openTransactionEntry } = useTransactionEntry()
  if (dashboard.isLoading) return <main className="product-page"><p>현재 예산을 불러오는 중입니다.</p></main>
  if (dashboard.isError) return <main className="product-page"><ErrorState onRetry={() => dashboard.refetch()}/></main>
  const data = dashboard.data
  if (!data) return <main className="product-page"><EmptyState title="대시보드를 준비하지 못했습니다." description="잠시 후 다시 시도해주세요."/></main>
  return <main className="product-page product-page--standard"><PageHeader eyebrow="DASHBOARD" title={`${data.ledger?.name ?? data.currentLedger.name}`} description={data.period ? `${data.period.startDate} — ${data.period.endDate}` : '현재 예산 기간'} actions={<div className="flex gap-2"><Link aria-label={`알림${notifications.data?.unreadCount ? ` ${notifications.data.unreadCount}개` : ''}`} className="relative flex size-11 items-center justify-center rounded-xl border border-[var(--wl-color-border)] bg-white" to="/notifications"><Bell aria-hidden="true" size={19}/>{notifications.data?.unreadCount ? <span className="absolute -right-1 -top-1 rounded-full bg-[var(--wl-color-danger)] px-1.5 text-[10px] font-bold text-white">{Math.min(99, notifications.data.unreadCount)}</span> : null}</Link><button className="hidden min-h-11 items-center gap-2 rounded-xl bg-[var(--wl-color-primary)] px-4 text-sm font-bold text-white sm:inline-flex" onClick={() => openTransactionEntry()} type="button"><Plus aria-hidden="true" size={18}/>빠른 기록</button></div>}/>
    {data.emptyState && data.emptyState !== 'READY' ? <DashboardEmptyState ledgerId={data.ledger?.id} state={data.emptyState}/> : null}
    <section aria-label="예산 사용 가능액" className="mt-5 grid gap-4 md:grid-cols-2">{data.sharedBudget ? <BudgetCard budget={data.sharedBudget} label="공동 예산"/> : null}{data.myBudget ? <BudgetCard budget={data.myBudget} label="내 예산"/> : null}</section>
    <section className="mt-5 grid gap-5 lg:grid-cols-[1.5fr_1fr]"><SurfaceCard><div className="flex items-center justify-between"><h2 className="font-bold">최근 거래</h2><Link className="text-sm font-bold text-[var(--wl-color-primary-dark)]" to="/transactions">전체 보기</Link></div>{data.recentTransactions.length ? <ul className="mt-4 divide-y divide-[var(--wl-color-border)]">{data.recentTransactions.slice(0,5).map((transaction) => <li className="flex min-h-[58px] items-center gap-3 py-3" key={transaction.id}><span className="min-w-0 flex-1"><strong className="block truncate">{transaction.merchant || transaction.memo || transaction.category?.name || '미분류 거래'}</strong><span className="mt-1 block text-xs text-[var(--wl-color-text-secondary)]">{transaction.transactionDate} · {transaction.scope?.type === 'SHARED' ? '공동 예산' : '내 예산'}</span></span><strong className="whitespace-nowrap tabular-nums">{transaction.type === 'EXPENSE' ? '-' : transaction.type === 'INCOME' ? '+' : ''}{formatWon(transaction.amount)}</strong></li>)}</ul> : <div className="mt-5"><EmptyState title="아직 거래가 없습니다." description="빠른 기록이나 이미지 가져오기로 첫 거래를 남겨보세요."/></div>}</SurfaceCard><div className="space-y-4"><SurfaceCard><span className="text-xs font-bold text-[var(--wl-color-text-secondary)]">기간 수입</span><strong className="mt-2 block text-xl tabular-nums">{formatWon(data.incomeAmount ?? 0)}</strong></SurfaceCard>{data.weeklyGuide ? <SurfaceCard><span className="text-xs font-bold text-[var(--wl-color-text-secondary)]">이번 주 가이드</span><strong className="mt-2 block text-xl tabular-nums">{formatWon(data.weeklyGuide.recommendedAmount)}</strong><p className="mt-2 text-sm text-[var(--wl-color-text-secondary)]">{data.weeklyGuide.weekStartDate} 시작 주간의 참고 금액입니다.</p></SurfaceCard> : null}</div></section>
  </main>
}

function BudgetCard({ label, budget }: { label: string; budget: DashboardBudget }) { const ratio=budget.amount>0?Math.round(budget.spentAmount/budget.amount*100):0; return <Link className="cursor-pointer rounded-[var(--wl-radius-lg)] border border-[var(--wl-color-border)] bg-white p-5 transition-colors hover:border-[var(--wl-color-border-strong)]" to="/budget"><span className="text-sm font-bold text-[var(--wl-color-text-secondary)]">{label} 사용 가능액</span><strong className={`mt-2 block text-3xl tabular-nums ${budget.availableAmount<0?'text-[var(--wl-color-danger)]':''}`}>{formatWon(budget.availableAmount)}</strong><div aria-label={`${label} ${ratio}% 사용`} className="mt-5 h-2 overflow-hidden rounded-full bg-[var(--wl-color-surface-subtle)]" role="progressbar" aria-valuemax={100} aria-valuemin={0} aria-valuenow={Math.min(100,ratio)}><span className="block h-full rounded-full bg-[var(--wl-color-primary)]" style={{width:`${Math.min(100,ratio)}%`}}/></div><div className="mt-3 flex justify-between text-xs text-[var(--wl-color-text-secondary)]"><span>사용 {formatWon(budget.spentAmount)}</span><span>전체 {formatWon(budget.amount)}</span></div></Link> }
function DashboardEmptyState({ state, ledgerId }: { state: 'INVITE_PARTNER' | 'ALLOCATE_BUDGET' | 'ADD_FIRST_TRANSACTION'; ledgerId?: number }) { const content={INVITE_PARTNER:['상대방 초대가 필요합니다.','초대 링크를 만들어 공동 장부를 함께 시작하세요.','장부 설정',ledgerId ? `/ledgers/${ledgerId}/settings` : '/dashboard'],ALLOCATE_BUDGET:['예산을 배분해주세요.','개인 예산과 공동 예산을 정하면 사용 가능액을 볼 수 있습니다.','예산 설정','/budget'],ADD_FIRST_TRANSACTION:['첫 거래를 기록해주세요.','예산이 준비됐습니다. 빠른 기록 또는 이미지 가져오기를 시작하세요.','이미지 가져오기','/transactions/import']}[state]; return <div className="mt-5"><EmptyState title={content[0]} description={content[1]} action={<Link className="inline-flex min-h-11 items-center rounded-xl bg-[var(--wl-color-primary)] px-4 text-sm font-bold text-white" to={content[3]}>{content[2]}</Link>}/></div> }
