import { Upload } from 'lucide-react'
import { useState } from 'react'
import { useMeQuery } from '../features/auth/model/authQueries'
import { useImportSessionPreviewMutation, useSaveImportSessionMutation } from '../features/import/model/transactionImportQueries'
import type { ImportSessionCandidate } from '../features/import/api/transactionImportApi'
import { EmptyState, ErrorState, PageHeader, SurfaceCard } from '../shared/ui/DesignPrimitives'

export function TransactionImportPage() {
  const me = useMeQuery()
  const ledgerId = me.data?.currentLedger.id
  const [files, setFiles] = useState<File[]>([])
  const [sourceType, setSourceType] = useState<'RECEIPT' | 'CARD_APP_SCREENSHOT'>('RECEIPT')
  const preview = useImportSessionPreviewMutation(ledgerId)
  const save = useSaveImportSessionMutation(ledgerId)
  const [selected, setSelected] = useState<Record<number, boolean>>({})
  const candidates = preview.data?.candidates ?? []
  function previewFiles() { preview.mutate({ images: files, sourceType }, { onSuccess: (data) => setSelected(Object.fromEntries(data.candidates.map((candidate) => [candidate.id, candidate.selectedByDefault]))) }) }
  function saveCandidates() { if (!preview.data) return; save.mutate({ sessionId: preview.data.sessionId, candidates: candidates.map((candidate) => toSaveCandidate(candidate, selected[candidate.id] ?? false)) }) }
  return <main className="product-page product-page--standard"><PageHeader eyebrow="IMPORT" title="이미지 가져오기" description="여러 영수증·카드 앱 캡처를 검토한 뒤 한 번에 저장합니다."/><SurfaceCard className="mt-5"><fieldset><legend className="text-sm font-bold">이미지 종류</legend><div className="mt-2 grid grid-cols-2 gap-2">{([['RECEIPT','영수증'],['CARD_APP_SCREENSHOT','카드 앱 캡처']] as const).map(([value,label]) => <button aria-pressed={sourceType === value} className="min-h-11 rounded-xl border border-[var(--wl-color-border)] text-sm font-bold aria-pressed:border-[var(--wl-brand-600)] aria-pressed:bg-[var(--wl-brand-100)]" key={value} onClick={() => setSourceType(value)} type="button">{label}</button>)}</div></fieldset><label className="mt-4 flex min-h-32 cursor-pointer flex-col items-center justify-center rounded-xl border border-dashed border-[var(--wl-color-border-strong)]"><Upload aria-hidden="true" size={24}/><strong className="mt-2">이미지 선택</strong><span className="mt-1 text-xs">PNG 또는 JPEG 여러 장</span><input accept="image/png,image/jpeg" className="sr-only" multiple onChange={(event)=>setFiles(Array.from(event.target.files??[]))} type="file"/></label>{files.length ? <button className="mt-3 min-h-11 rounded-xl bg-[var(--wl-color-primary)] px-4 text-sm font-bold text-white" disabled={preview.isPending} onClick={previewFiles} type="button">{preview.isPending ? '인식 중...' : `${files.length}장 인식하기`}</button> : null}</SurfaceCard>
    {preview.isError ? <div className="mt-5"><ErrorState onRetry={()=>preview.reset()}/></div> : null}{preview.isSuccess && !candidates.length ? <div className="mt-5"><EmptyState title="확인 가능한 거래가 없습니다." description="더 선명한 이미지나 필요한 영역만 잘라 다시 시도해주세요."/></div> : null}
    {candidates.length ? <SurfaceCard className="mt-5"><div className="flex items-center justify-between gap-4"><h2 className="font-bold">검토할 거래 {candidates.length}건</h2>{preview.data?.omittedCount ? <span className="text-xs font-bold text-[var(--wl-color-text-secondary)]">신뢰하기 어려운 {preview.data.omittedCount}건 제외</span> : null}</div><ul className="mt-3 divide-y divide-[var(--wl-color-border)]">{candidates.map((candidate) => <li className={`py-4 ${candidate.duplicateSuspected ? 'rounded-xl border border-[var(--wl-color-danger)] px-3' : ''}`} key={candidate.id}><label className="flex cursor-pointer items-start gap-3"><input checked={selected[candidate.id] ?? false} className="mt-1" onChange={(event)=>setSelected((current)=>({...current,[candidate.id]:event.target.checked}))} type="checkbox"/><span className="min-w-0 flex-1"><strong className="block truncate">{candidate.merchant}</strong><span className="mt-1 block text-xs text-[var(--wl-color-text-secondary)]">{candidate.occurredOn} · {candidate.amount.toLocaleString()}원 · {candidate.suggestedCategoryId ? '추천 카테고리 적용' : '미분류'}</span>{candidate.duplicateSuspected ? <span className="mt-1 block text-xs font-bold text-[var(--wl-color-danger)]">중복 가능성이 있어 기본 선택에서 제외했습니다.</span> : null}</span></label></li>)}</ul>{save.isError ? <p className="mt-3 text-sm text-[var(--wl-color-danger)]" role="alert">후보를 다시 확인한 뒤 저장해주세요.</p> : null}<button className="mt-4 min-h-11 rounded-xl bg-[var(--wl-color-primary)] px-4 text-sm font-bold text-white disabled:bg-slate-300" disabled={save.isPending || !Object.values(selected).some(Boolean)} onClick={saveCandidates} type="button">{save.isPending ? '저장 중...' : '선택한 거래 저장'}</button></SurfaceCard> : null}
  </main>
}

function toSaveCandidate(candidate: ImportSessionCandidate, selected: boolean) { return { candidateId: candidate.id, amount: candidate.amount, occurredOn: candidate.occurredOn, merchant: candidate.merchant, categoryId: candidate.suggestedCategoryId, budgetSource: candidate.suggestedAllocation, selected } }
